[[CURRENCIES]]
code="AIWAY"
issuer="GBYNA57Q5KXQ6Q3JG35FTLXRGEPYUONM7TYV6TXFJRRWZPDUDHNQSY27"
name="AiWay"
desc="AiWay is an all-in-one Ai platform for chatting, image generation, and accessing powerful language models through a simple interface."
image="https://github.com/medomohamed22/Tokens/blob/main/AiWay.jpg"

